### ISSUE TITLE
The tunable parameters of VPT+Bias for Semantic Segmentation

### ISSUE THREAD

**Issue by liulingbo918** [KMnP/vpt#13]
Can you provide more details of different methods and their tunable parameters in Table 4 for semantic segmentation? 

Except for header parameters：
1）the tunable parameter number of BIAS is 13.46-13.18=0.28M
2）the tunable parameter number of VPT is 13.43-13.18=0.25M
3)  why is the tunable parameter number of VPT+BIAS 15.79-13.18=2.61M,  rather than 0.28+0.25=0.53M？

It seems to me that  BIAS was reimplemented based on the paper [5] (fine-tunes only the bias terms). 
However, was VPT+BIAS reimplemented based on the paper [8] (fine-tunes the bias terms and introduces some lightweight residual layers)?

![image](https://user-images.githubusercontent.com/7027922/194030269-622b844a-3c4f-41a1-9a17-6634899b6a38.png)
![image](https://user-images.githubusercontent.com/7027922/194035428-62e57df6-9118-466a-8b4a-db3f15371f71.png)

**Comment by KMnP** [comment]
Hi @liulingbo918 Thanks for your question. The reason for this difference is that VPT-deep and VPT+Bias use different number of prompts as hyperparameter. VPT-deep uses `p=10`, whereas VPT+BIAS uses `p=100`.  Since VPT+BIAS use 10 times of prompts than VPT_deep, the tunable parameters of VPT+BIAS = 0.28 + 0.25 **x10**

Let me know if you have more questions!

**Comment by liulingbo918** [comment]
@KMnP Thanks for your reply. A good work!
